version: "3"
services:
  fumblestore:
    build:
      context: ../..
      dockerfile: src/fumblechain/docker/fumblestore/Dockerfile
    ports:
      - "${HOST_BIND_ADDRESS}:${FUMBLESTORE_PORT}:${FUMBLESTORE_PORT}"
    environment:
      - CHALLENGE1_PRODUCT_NODE_API_URL=http://mainnet-node:1337
      - CHALLENGE2_PRODUCT_NODE_API_URL=http://mainnet2-node:1337
      - CHALLENGE3_PRODUCT_NODE_API_URL=http://mainnet3-node:1337
      # challenge 1
      - CHALLENGE1_MONEYMAKER_URL=http://${FC_HOST}:${CH1_MONEYMAKER_PORT}
      - CHALLENGE1_MAINNET_NODE_URL=${FC_HOST}:${CH1_MAINNET_NODE_PORT}
      - CHALLENGE1_MAINNET_NODE_HOST=mainnet-node
      - CHALLENGE1_TESTNET_NODE_URL=${FC_HOST}:${CH1_TESTNET_NODE_PORT}
      - CHALLENGE1_TESTNET_NODE_HOST=testnet-node
      - CHALLENGE1_TESTNET_MAGIC=${CH1_TESTNET_MAGIC}
      # challenge 2
      - CHALLENGE2_MAINNET2_NODE_URL=${FC_HOST}:${CH2_MAINNET_NODE_PORT}
      - CHALLENGE2_MAINNET2_NODE_HOST=mainnet2-node
      - CHALLENGE2_MAINNET2_MAGIC=${CH2_MAINNET_MAGIC}
      # challenge 3
      - CHALLENGE3_MAINNET3_NODE_URL=${FC_HOST}:${CH3_MAINNET_NODE_PORT}
      - CHALLENGE3_MAINNET3_NODE_HOST=mainnet3-node
      - CHALLENGE3_MAINNET3_MAGIC=${CH3_MAINNET_MAGIC}
      - CHALLENGE3_ECHOSERVICE_MIN_CONFIRMATIONS=${CH3_ECHOSERVICE_MIN_CONFIRMATIONS}
      # fumblestore
      - SQLITE_DATABASE_PATH=/opt/fumblechain/volume/fumblestore.sqlite
      - FUMBLESTORE_PORT
      - IS_DOCKER_LOCAL
      - FLASK_DEBUG=${DEBUG}
    env_file:
      - gen/fumblestore_secret_key.env
      - gen/echoservice.env
      - .env
    volumes:
      - /opt/fumblechain/volume
      # for development
  #      - ./:/opt/fumblechain/src/fumblechain

  # challenge 1
  moneymaker:
    build:
      context: ../..
      dockerfile: src/fumblechain/docker/challenge1/moneymaker/Dockerfile
    ports:
      - "${HOST_BIND_ADDRESS}:${CH1_MONEYMAKER_PORT}:${CH1_MONEYMAKER_PORT}"
    environment:
      - CHALLENGE1_MONEYMAKER_URL=http://${FC_HOST}:${CH1_MONEYMAKER_PORT}
      - CHALLENGE1_MAINNET_NODE_URL=${FC_HOST}:${CH1_MAINNET_NODE_PORT}
      - CHALLENGE1_TESTNET_NODE_URL=${FC_HOST}:${CH1_TESTNET_NODE_PORT}
      - CHALLENGE1_TESTNET_MAGIC=${CH1_TESTNET_MAGIC}
      - CHALLENGE1_MONEYMAKER_CLIENT_API_HOST=http://testnet-node:1337
      - CHALLENGE1_MONEYMAKER_WALLET_PATH=wallets/moneymaker.wallet
      - CHALLENGE1_MONEYMAKER_TX_AMOUNT=5000000
      - CH1_MONEYMAKER_PORT
  mainnet-node:
    build:
      context: ../..
      dockerfile: src/fumblechain/docker/challenge1/mainnet-node/Dockerfile
    ports:
      - "${HOST_BIND_ADDRESS}:${CH1_MAINNET_NODE_PORT}:${CH1_MAINNET_NODE_PORT}"
    env_file:
      - gen/ctf_wallet_addresses_ch1.env
    environment:
      - CH1_MAINNET_NODE_PORT
      - FUMBLECHAIN_BLOCKCHAIN_PATH
    volumes:
      - /opt/fumblechain/bc-volume
  testnet-node:
    build:
      context: ../..
      dockerfile: src/fumblechain/docker/challenge1/testnet-node/Dockerfile
    ports:
      - "${HOST_BIND_ADDRESS}:${CH1_TESTNET_NODE_PORT}:${CH1_TESTNET_NODE_PORT}"
    env_file:
      - gen/ctf_wallet_addresses_ch1.env
    environment:
      - CH1_TESTNET_NODE_PORT
      - CH1_TESTNET_MAGIC
      - FUMBLECHAIN_BLOCKCHAIN_PATH
    volumes:
      - /opt/fumblechain/bc-volume

  # challenge 2
  mainnet2-node:
    build:
      context: ../..
      dockerfile: src/fumblechain/docker/challenge2/mainnet2-node/Dockerfile
    ports:
      - "${HOST_BIND_ADDRESS}:${CH2_MAINNET_NODE_PORT}:${CH2_MAINNET_NODE_PORT}"
    environment:
      - CHALLENGE2_MAINNET2_NODE_URL=${FC_HOST}:${CH2_MAINNET_NODE_PORT}
      - CHALLENGE2_MAINNET2_MAGIC=${CH2_MAINNET_MAGIC}
      - CH2_MAINNET_NODE_PORT
      - CH2_MAINNET_MAGIC
      - CHALLENGE2_WALLET_A_PATH=wallets/ch2a.wallet
      - CHALLENGE2_WALLET_B_PATH=wallets/ch2b.wallet
      - FUMBLECHAIN_BLOCKCHAIN_PATH
    env_file:
      - gen/ctf_wallet_addresses_ch2.env
    volumes:
      - /opt/fumblechain/bc-volume

  # challenge 3
  mainnet3-node:
    build:
      context: ../..
      dockerfile: src/fumblechain/docker/challenge3/mainnet3-node/Dockerfile
    ports:
      - "${HOST_BIND_ADDRESS}:${CH3_MAINNET_NODE_PORT}:${CH3_MAINNET_NODE_PORT}"
    environment:
      - CH3_MAINNET_NODE_PORT
      - CH3_MAINNET_MAGIC
      - FUMBLECHAIN_BLOCKCHAIN_PATH
    env_file:
      - gen/ctf_wallet_addresses_ch3.env
    volumes:
      - /opt/fumblechain/bc-volume

  echoservice:
    build:
      context: ../..
      dockerfile: src/fumblechain/docker/challenge3/echoservice/Dockerfile
    environment:
      - CH3_ECHOSERVICE_SLEEP_INTERVAL_SECONDS=10
      - CH3_ECHOSERVICE_MIN_CONFIRMATIONS
      - CH3_ECHOSERVICE_WALLET_PATH=wallets/echoservice.wallet
      - CH3_MAINNET_API_URL=http://mainnet3-node:1337
    volumes:
      - /opt/fumblechain/src/fumblechain/persistent


